#!/usr/bin/env bash
#
# Deedy Automation - one-click launcher.
#
# Brings up the app (and optionally a local Ollama server), waits until the API
# is healthy, and prints where to go. Nothing here runs at system boot: the
# compose services use restart: "no", so the stack only ever starts when you
# run this script.
#
#   ./start.sh                 app only
#   ./start.sh --llm           app + Ollama
#   ./start.sh --llm --pull    app + Ollama, and pull $DEEDY_MODEL first
#   ./start.sh --rebuild       force an image rebuild
#   ./start.sh --stop          stop everything
#   ./start.sh --logs          follow the app logs
#   ./start.sh --status        show what is running
#
set -Eeuo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")"

APP_PORT="${APP_PORT:-8080}"
OLLAMA_PORT="${OLLAMA_PORT:-11434}"
DEEDY_MODEL="${DEEDY_MODEL:-qwen3:8b}"
HEALTH_TIMEOUT="${HEALTH_TIMEOUT:-180}"

if [[ -t 1 ]] && [[ -z "${NO_COLOR:-}" ]]; then
  BOLD=$'\033[1m'; DIM=$'\033[2m'; RED=$'\033[31m'; GREEN=$'\033[32m'
  YELLOW=$'\033[33m'; BLUE=$'\033[34m'; RESET=$'\033[0m'
else
  BOLD=''; DIM=''; RED=''; GREEN=''; YELLOW=''; BLUE=''; RESET=''
fi

say()  { printf '%s==>%s %s\n' "$BLUE$BOLD" "$RESET" "$*"; }
ok()   { printf '%s  ok%s %s\n' "$GREEN" "$RESET" "$*"; }
warn() { printf '%s  !!%s %s\n' "$YELLOW" "$RESET" "$*"; }
die()  { printf '%s error:%s %s\n' "$RED$BOLD" "$RESET" "$*" >&2; exit 1; }

# --------------------------------------------------------------------------
# Argument parsing
# --------------------------------------------------------------------------
WITH_LLM=0
PULL_MODEL=0
REBUILD=0
ACTION=up

while [[ $# -gt 0 ]]; do
  case "$1" in
    --llm)      WITH_LLM=1 ;;
    --pull)     WITH_LLM=1; PULL_MODEL=1 ;;
    --rebuild)  REBUILD=1 ;;
    --stop|--down) ACTION=stop ;;
    --logs)     ACTION=logs ;;
    --status|--ps) ACTION=status ;;
    --model)    shift; DEEDY_MODEL="${1:-}" ;;
    -h|--help)  sed -n '3,17p' "${BASH_SOURCE[0]}" | sed 's/^#\{1\} \{0,1\}//'; exit 0 ;;
    *)          die "unknown option: $1 (try --help)" ;;
  esac
  shift
done

# --------------------------------------------------------------------------
# Preflight
# --------------------------------------------------------------------------
command -v docker >/dev/null 2>&1 || die "docker is not installed or not on PATH"
docker compose version >/dev/null 2>&1 || die "the 'docker compose' plugin is required (v2)"
docker info >/dev/null 2>&1 || die "cannot talk to the Docker daemon - is it running, and is your user in the 'docker' group?"

COMPOSE=(docker compose)
[[ $WITH_LLM -eq 1 ]] && COMPOSE+=(--profile llm)

# Fail with a useful message rather than Docker's raw bind error.
port_taken() {
  local port="$1"
  if command -v ss >/dev/null 2>&1; then
    ss -ltn "sport = :${port}" 2>/dev/null | grep -q LISTEN
  elif command -v netstat >/dev/null 2>&1; then
    netstat -ltn 2>/dev/null | grep -q ":${port} "
  else
    return 1
  fi
}

check_port() {
  local port="$1" label="$2" ours="$3"
  port_taken "$port" || return 0
  # Our own container holding the port just means the stack is already up.
  docker ps --format '{{.Names}}' | grep -qx "$ours" && return 0
  local owner
  owner="$(docker ps --format '{{.Names}}\t{{.Ports}}' | grep -m1 ":${port}->" | cut -f1 || true)"
  die "port ${port} (${label}) is already in use${owner:+ by the container '${owner}'}.
       Pick another with:  ${label}=<port> ./start.sh${WITH_LLM:+ --llm}
       or edit ${label} in .env"
}

# --------------------------------------------------------------------------
# Non-"up" actions
# --------------------------------------------------------------------------
case "$ACTION" in
  stop)
    say "Stopping Deedy Automation"
    docker compose --profile llm down
    ok "stopped - your data volume is untouched"
    exit 0
    ;;
  logs)
    exec docker compose logs -f app
    ;;
  status)
    docker compose --profile llm ps
    exit 0
    ;;
esac

# --------------------------------------------------------------------------
# Generate a persistent encryption key on first run.
#
# Without this the container generates a key inside the data volume, which is
# fine - but pinning it in .env means the volume can be restored onto a fresh
# host and still decrypt stored secrets.
# --------------------------------------------------------------------------
if [[ ! -f .env ]]; then
  say "First run - creating .env"
  KEY="$(openssl rand -hex 32 2>/dev/null || docker run --rm "${IMAGE:-node:22-bookworm-slim}" \
        node -e 'process.stdout.write(require("crypto").randomBytes(32).toString("hex"))')"
  cat > .env <<EOF
# Generated by start.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Losing ENCRYPTION_KEY makes stored secrets (LLM API key, webhook URL)
# unrecoverable. Back this file up alongside the data volume.
ENCRYPTION_KEY=$KEY
APP_PORT=$APP_PORT
OLLAMA_PORT=$OLLAMA_PORT
LOG_LEVEL=info
EOF
  chmod 600 .env
  ok ".env created with a fresh 32-byte encryption key"
else
  ok ".env found - reusing the existing encryption key"
fi

# --------------------------------------------------------------------------
# Bring the stack up
# --------------------------------------------------------------------------
if [[ $REBUILD -eq 1 ]]; then
  say "Rebuilding the image (this pulls Chromium and Firefox, so give it a few minutes)"
  "${COMPOSE[@]}" build --no-cache app
elif ! docker image inspect deedy-automation:latest >/dev/null 2>&1; then
  say "Building the image for the first time (this pulls Chromium and Firefox, so give it a few minutes)"
  "${COMPOSE[@]}" build app
fi

check_port "$APP_PORT" APP_PORT deedy-app
[[ $WITH_LLM -eq 1 ]] && check_port "$OLLAMA_PORT" OLLAMA_PORT deedy-ollama

say "Starting services"
"${COMPOSE[@]}" up -d --build

# --------------------------------------------------------------------------
# Wait for health
# --------------------------------------------------------------------------
say "Waiting for the API to become healthy (up to ${HEALTH_TIMEOUT}s)"
deadline=$(( SECONDS + HEALTH_TIMEOUT ))
until curl -fsS "http://127.0.0.1:${APP_PORT}/api/health/live" >/dev/null 2>&1; do
  if (( SECONDS >= deadline )); then
    printf '\n'
    warn "the API did not become healthy in time - last 40 log lines:"
    docker compose logs --tail 40 app
    die "startup failed"
  fi
  if ! docker compose ps --status running --services 2>/dev/null | grep -qx app; then
    printf '\n'
    warn "the app container exited - last 40 log lines:"
    docker compose logs --tail 40 app
    die "startup failed"
  fi
  printf '.'
  sleep 2
done
printf '\n'
ok "API is live"

# --------------------------------------------------------------------------
# Optional: pull a model into the bundled Ollama
# --------------------------------------------------------------------------
if [[ $WITH_LLM -eq 1 ]]; then
  say "Waiting for Ollama"
  deadline=$(( SECONDS + 120 ))
  until curl -fsS "http://127.0.0.1:${OLLAMA_PORT}/api/tags" >/dev/null 2>&1; do
    (( SECONDS >= deadline )) && die "Ollama did not come up on port ${OLLAMA_PORT}"
    printf '.'
    sleep 2
  done
  printf '\n'
  ok "Ollama is live on port ${OLLAMA_PORT}"

  if [[ $PULL_MODEL -eq 1 ]]; then
    if docker compose exec -T ollama ollama list 2>/dev/null | grep -q "^${DEEDY_MODEL%%:*}"; then
      ok "model ${DEEDY_MODEL} is already present"
    else
      say "Pulling ${DEEDY_MODEL} (several GB - only happens once)"
      docker compose exec -T ollama ollama pull "$DEEDY_MODEL"
      ok "model ${DEEDY_MODEL} pulled"
    fi
  fi

  # Point the app at the sibling container rather than localhost. The app runs
  # in its own container, so "localhost" would resolve to the app itself.
  say "Pointing the app at the bundled Ollama"
  llm_patch='{"provider":"ollama","baseUrl":"http://ollama:11434"'
  if [[ $PULL_MODEL -eq 1 ]]; then
    llm_patch+=",\"model\":\"${DEEDY_MODEL}\""
  fi
  llm_patch+='}'

  if curl -fsS -X PATCH "http://127.0.0.1:${APP_PORT}/api/settings" \
       -H 'content-type: application/json' \
       -d "{\"llm\":${llm_patch}}" >/dev/null; then
    if [[ $PULL_MODEL -eq 1 ]]; then
      ok "LLM endpoint configured (model: ${DEEDY_MODEL})"
    else
      ok "LLM endpoint configured (choose a model in Settings -> Local LLM)"
    fi
  else
    warn "could not configure the LLM endpoint automatically - set it in Settings -> Local LLM"
  fi
fi

# --------------------------------------------------------------------------
# Summary
# --------------------------------------------------------------------------
STATUS_JSON="$(curl -fsS "http://127.0.0.1:${APP_PORT}/api/health" 2>/dev/null || echo '{}')"
LLM_OK="$(printf '%s' "$STATUS_JSON" | grep -o '"reachable":[a-z]*' | head -1 | cut -d: -f2)"

printf '\n%sDeedy Automation is running%s\n\n' "$BOLD$GREEN" "$RESET"
printf '  Dashboard   %shttp://localhost:%s%s\n' "$BOLD" "$APP_PORT" "$RESET"
printf '  API docs    %shttp://localhost:%s/docs%s\n' "$DIM" "$APP_PORT" "$RESET"
printf '  Health      %shttp://localhost:%s/api/health%s\n' "$DIM" "$APP_PORT" "$RESET"
[[ $WITH_LLM -eq 1 ]] && printf '  Ollama      %shttp://localhost:%s%s\n' "$DIM" "$OLLAMA_PORT" "$RESET"

printf '\n%sNext steps%s\n' "$BOLD" "$RESET"
if [[ "${LLM_OK:-false}" != "true" ]]; then
  printf '  1. Settings -> Local LLM: point at your inference server and choose a model.\n'
else
  printf '  1. Settings -> Local LLM: confirm the model selection.\n'
fi
printf '  2. Resume Manager: add a base resume.\n'
printf '  3. Settings -> Search: add keywords and company boards.\n'
printf '  4. Leave %sdry run ON%s until you have watched a few applications run.\n' "$BOLD" "$RESET"

printf '\n%sThis stack does not start at boot.%s Use ./start.sh to start, ./start.sh --stop to stop.\n' "$DIM" "$RESET"
printf '%sFollow logs with ./start.sh --logs%s\n\n' "$DIM" "$RESET"
